### PR TITLE
add gelu activation to fp32 list

### LINKED ISSUE #555: RuntimeError: "GeluCUDAKernelImpl" not implemented for 'Half'
PyTorch 1.2 introduced the `gelu` activation function. Unfortunately, this leads to terminal errors when using with AMP.

Trace (`self.activation` is `gelu`): 

```
Traceback (most recent call last):
  File "predict.py", line 282, in <module>
    predictor.predict()
  File "predict.py", line 74, in predict
    fig = trainer.train()
  File "/home/bram/Python/projects/transformer-classifiers/transformer_classifiers/TransformerTrainer.py", line 232, in train
    self._process('train', epoch)
  File "/home/bram/Python/projects/transformer-classifiers/transformer_classifiers/TransformerTrainer.py", line 124, in _process
    preds = self.model(input_ids, attention_mask=input_mask)
  File "/home/bram/.local/share/virtualenvs/transformer-classifiers-x27iJBv7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bram/.local/share/virtualenvs/transformer-classifiers-x27iJBv7/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 442, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/bram/.local/share/virtualenvs/transformer-classifiers-x27iJBv7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bram/Python/projects/transformer-classifiers/transformer_classifiers/models.py", line 140, in forward
    cls_output = self.activation(cls_output)
  File "/home/bram/.local/share/virtualenvs/transformer-classifiers-x27iJBv7/lib/python3.7/site-packages/torch/nn/functional.py", line 1126, in gelu
    return torch._C._nn.gelu(input)
RuntimeError: "GeluCUDAKernelImpl" not implemented for 'Half'
```

### PR DESCRIPTION
**Pull request by BramVanroy**
closes #555

### CODE REVIEW

**Comment by BramVanroy** [comment]
From my testing, this should be rolled back (or at least ignored). It worked when I just used my custom gelu function, but issues occur when using PyTorch's implementation. A fix seems to be in the making here https://github.com/pytorch/pytorch/pull/28944

**Comment by ptrblck** [comment]
@BramVanroy which errors are you seeing?
Since the mentioned PR was merged, should we revert this PR @mcarilli?

**Comment by BramVanroy** [comment]
> @BramVanroy which errors are you seeing?
> Since the mentioned PR was merged, should we revert this PR @mcarilli?

Here's the trace:

```bash
Traceback (most recent call last):
  File "C:/dev/python/transformer-classifiers/transformer_classifiers/predict.py", line 281, in <module>
    predictor.predict()
  File "C:/dev/python/transformer-classifiers/transformer_classifiers/predict.py", line 74, in predict
    fig = trainer.train()
  File "C:\dev\python\transformer-classifiers\transformer_classifiers\TransformerTrainer.py", line 237, in train
    self._process('train', epoch)
  File "C:\dev\python\transformer-classifiers\transformer_classifiers\TransformerTrainer.py", line 125, in _process
    preds = self.model(input_ids, attention_mask=input_mask)
  File "C:\Users\bramv\.virtualenvs\transformer-classifiers-yxkdICkg\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\dev\python\transformer-classifiers\transformer_classifiers\models.py", line 140, in forward
    cls_output = self.activation(cls_output)
  File "C:\Users\bramv\.virtualenvs\transformer-classifiers-yxkdICkg\lib\site-packages\torch\nn\functional.py", line 1126, in gelu
    return torch._C._nn.gelu(input)
RuntimeError: "GeluCUDAKernelImpl" not implemented for 'Half'
```

But as I said before, this _might_ be a PyTorch issue, particularly https://github.com/pytorch/pytorch/pull/28944

**Comment by ptrblck** [comment]
This should be fixed by https://github.com/pytorch/pytorch/pull/28944 
@BramVanroy Can you verify it with the PyTorch nightly build?

**Comment by BramVanroy** [comment]
> This should be fixed by [pytorch/pytorch#28944](https://github.com/pytorch/pytorch/pull/28944)
> @BramVanroy Can you verify it with the PyTorch nightly build?

Seems to work, indeed. I tested the snippet in https://github.com/NVIDIA/apex/pull/564#issuecomment-552242536 on nightly and it runs fine. Just to be sure, I tested `nn.functional.gelu` as well as `nn.GELU()`. Both work!

**Pull request merged**
