### PR TITLE
Multi tensor lamb optimizer

### PR DESCRIPTION
**Pull request by thorjohnsen**
Two stage implementation of LAMB optimizer.

### CODE REVIEW

**Comment by mcarilli** [comment]
Looks fine but compile time is getting a little high.  Eventually we should reorganize this to be compiled optionally.

**Comment by francoishernandez** [comment]
Hey guys,
Is there some WIP going on to go all the way and add the `fused_lamb_cuda` C++ wrapper and the `apex.optimizers.FusedLamb` python class?
If not, we might have a look, as we're interested in adding this for [OpenNMT-py](https://github.com/OpenNMT/OpenNMT-py).

**Comment by mcarilli** [comment]
@francoishernandez Yes, we definitely plan to expose this via a `apex.optimizers.FusedLamb` Python class.  @sharatht has a local implementation, which we are still testing (not present on Github yet).

**Comment by francoishernandez** [comment]
Great, thanks for your prompt reply ans the good news!

**Pull request merged**
